# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# from https://gist.github.com/andreptb/57e388df5e881937e62a

# box name into env var, same script can be used with different boxes. Defaults to win7-ie11.
box_name = box_name = ENV['box_name'] != nil ? ENV['box_name'].strip : 'win7-ie11'
# box repo into env var, so private repos/cache can be used. Defaults to http://aka.ms
box_repo = ENV['box_repo'] != nil ? ENV['box_repo'].strip : 'http://aka.ms'

Vagrant.configure("2") do |config|
  # If the box is win7-ie11, the convention for the box name is modern.ie/win7-ie11
  config.vm.box = "modern.ie/" + box_name
  # If the box is win7-ie11, the convention for the box url is http://aka.ms/vagrant-win7-ie11
  config.vm.box_url = box_repo + "/vagrant-" + box_name
  # big timeout since windows boot is very slow
  config.vm.boot_timeout = 500

  # port forwards
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  # winrm config, uses modern.ie default user/password. If other credentials are used must be changed here
  config.vm.communicator = "winrm"
  config.winrm.host = "localhost"
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"

  # install gpg4win, and latest libreoffice master
  config.vm.provision :shell, inline: "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))"
  config.vm.provision :shell, inline: "C:\\ProgramData\\chocolatey\\bin\\choco install -y gpg4win"
  config.vm.provision :shell, inline: "(new-object net.webclient).DownloadFile('http://librebuildix.cib.de:8080/job/LibreOffice%20master%20Win%2032+64bit/distro=LibreOfficeWin32,label=windows-builder/lastSuccessfulBuild/artifact/*zip*/archive.zip', 'C:\\Windows\\Temp\\libo.zip')"
  config.vm.provision :shell, inline: "$shell = new-object -com shell.application ; New-Item -ItemType Directory -Path 'C:\\Windows\\Temp\\libo' -Force -WarningAction SilentlyContinue ; $shell.namespace('C:\\Windows\\Temp\\libo').copyhere($shell.namespace('C:\\Windows\\Temp\\libo.zip').items())"
  config.vm.provision :shell, inline: "$shell = new-object -com shell.application ; foreach ($item in $shell.namespace('C:\\Windows\\Temp\\libo\\archive').items()) { Write-Output $item ; Start-Process 'msiexec' -ArgumentList (\"/qb /i \" + $item.Path + \" /L* C:\\Windows\\Temp\\libo.log\") -NoNewWindow -Wait }"
  config.vm.provision :shell, inline: "Remove-Item -Recurse -Force 'C:\\Windows\\Temp\\libo' ; Remove-Item -Recurse -Force 'C:\\Windows\\Temp\\libo.zip'"

  config.vm.guest = :windows
  config.vm.provider "virtualbox" do |vb|
    # first setup requires gui to be enabled so scripts can be
    # executed in virtualbox guest screen - disable now
    vb.gui = false
    vb.name = "gpg4libre Win7"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id,  "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
  end
end
